
[spawn]
	#Set true to allow Senpai to spawn naturally
	spawn_senpai = false
	#this feature is under development, DO NOT TURN THIS ON!
	spawn_mob_with_guns = false

[projectile]
	#Set true to allow projectiles to destroy certain blocks
	allow_projectile_destroy_blocks = false

[explosion]
	#The percentage of explosion damage you take behind cover
	#Range: 0 ~ 100
	explosion_penetration_ratio = 15
	#Set true to allow Explosion to destroy blocks
	explosion_destroy = true

	[explosion."RGO Grenade"]
		#The explosion damage of RGO grenade
		#Range: 1 ~ 10000000
		rgo_grenade_explosion_damage = 90
		#The explosion radius of RGO grenade
		#Range: 1 ~ 50
		rgo_grenade_explosion_radius = 5

	[explosion."M67 Grenade"]
		#The explosion damage of M67 grenade
		#Range: 1 ~ 10000000
		m67_grenade_explosion_damage = 120
		#The explosion radius of M67 grenade
		#Range: 1 ~ 50
		m67_grenade_explosion_radius = 6

	[explosion."Mortar Shell"]
		#The explosion damage of Mortar shell
		#Range: 1 ~ 10000000
		mortar_shell_explosion_damage = 160
		#The explosion radius of Mortar shell
		#Range: 1 ~ 50
		mortar_shell_explosion_radius = 9

	[explosion."Drone Kamikaze"]
		#The explosion damage of Drone Kamikaze
		#Range: 1 ~ 10000000
		drone_kamikaze_explosion_damage = 160
		#The explosion radius of Drone Kamikaze
		#Range: 1 ~ 50
		drone_kamikaze_explosion_radius = 9

	[explosion.C4]
		#The explosion damage of C4
		#Range: > 1
		c4_explosion_damage = 300
		#The explosion countdown of C4
		#Range: > 1
		c4_explosion_countdown = 514
		#The explosion radius of C4
		#Range: > 1
		c4_explosion_radius = 10

	[explosion."Wire Guide Missile"]
		#The damage of wire guide missile
		#Range: > 1
		wire_guide_missile_damage = 700
		#The explosion damage of wire guide missile
		#Range: > 1
		wire_guide_missile_explosion_damage = 60
		#The explosion radius of wire guide missile
		#Range: > 1
		wire_guide_missile_explosion_radius = 6

	[explosion.RPG]
		#The explosion damage of RPG in the drone
		#Range: > 1
		rpg_explosion_damage = 130
		#The explosion radius of RPG in the drone
		#Range: > 1
		rpg_explosion_radius = 10

	[explosion.AGM-65]
		#The damage of AGM-65
		#Range: > 1
		agm_65_damage = 1100
		#The explosion damage of AGM-65
		#Range: > 1
		agm_65_explosion_damage = 150
		#The explosion radius of AGM-65
		#Range: 1.0 ~ 2.147483647E9
		agm_65_explosion_radius = 9.0

	[explosion.MK-82]
		#The explosion damage of MK-82
		#Range: > 1
		mk_82_explosion_damage = 650
		#The explosion radius of MK-82
		#Range: 1.0 ~ 2.147483647E9
		mk_82_explosion_radius = 22.0

[vehicle]
	#Allows vehicles to destroy soft blocks via collision
	collision_destroy_soft_blocks = false
	#Allows vehicles to destroy normal blocks via collision
	collision_destroy_normal_blocks = false
	#Allows vehicles to destroy hard blocks via collision
	collision_destroy_hard_blocks = false
	#Allows vehicles to destroy blocks via collision like a beast
	collision_destroy_blocks_beastly = false
	#Allow vehicles to pick up items
	vehicle_item_pickup = true
	#Allow vehicles to collect drops after killing other entities by crashing
	collect_drops_by_crashing = true
	#List of entities that can be damaged by collision
	collision_entity_whitelist = []

	[vehicle.repair]
		#The default cooldown of vehicle repair. Set a negative value to disable vehicle repair
		#Range: -1 ~ 100000000
		repair_cooldown = 200
		#The default amount of health restored per tick when a vehicle is self-repairing
		#Range: -1.0E8 ~ 1.0E8
		repair_amount = 0.05
		#Within this distance, the vehicle info will be displayed at client side
		#Range: 0 ~ 1024
		vehicle_info_display_distance = 512

	[vehicle.MK-42]
		#The AP shell damage of MK-42
		#Range: 1 ~ 10000000
		mk_42_ap_damage = 450
		#The AP shell explosion damage of MK-42
		#Range: 1 ~ 10000000
		mk_42_ap_explosion_damage = 120
		#The AP shell explosion radius of MK-42
		#Range: 1 ~ 50
		mk_42_ap_explosion_radius = 3
		#The HE shell damage of MK-42
		#Range: 1 ~ 10000000
		mk_42_he_damage = 150
		#The HE shell explosion damage of MK-42
		#Range: 1 ~ 10000000
		mk_42_he_explosion_damage = 200
		#The HE shell explosion radius of MK-42
		#Range: 1 ~ 50
		mk_42_he_explosion_radius = 10

	[vehicle.MLE-1934]
		#The AP shell damage of MLE-1934
		#Range: 1 ~ 10000000
		mle_1934_ap_damage = 500
		#The AP shell explosion damage of MLE-1934
		#Range: 1 ~ 10000000
		mle_1934_ap_explosion_damage = 150
		#The AP shell explosion radius of MLE-1934
		#Range: 1 ~ 50
		mle_1934_ap_explosion_radius = 4
		#The HE shell damage of MLE-1934
		#Range: 1 ~ 10000000
		mle_1934_he_damage = 180
		#The HE shell explosion damage of MLE-1934
		#Range: 1 ~ 10000000
		mle_1934_he_explosion_damage = 240
		#The HE shell explosion radius of MLE-1934
		#Range: 1 ~ 50
		mle_1934_he_explosion_radius = 12

	[vehicle."Heavy Machine Gun"]
		#The gun damage of 12.7mm HMG
		#Range: 1 ~ 10000000
		heavy_machine_gun_damage = 40

	[vehicle.Annihilator]
		#The energy cost of Annihilator per shoot
		#Range: > 0
		annihilator_shoot_cost = 2000000

	[vehicle."Laser Tower"]
		#The damage of Laser Tower
		#Range: 1 ~ 10000000
		laser_tower_damage = 15
		#The cooldown time(ticks) of Laser Tower
		#Range: 15 ~ 10000000
		laser_tower_cooldown = 40
		#The energy cost of Laser Tower per shoot
		#Range: > 0
		laser_tower_shoot_cost = 5000

	[vehicle.Speedboat]
		#The energy cost of Speedboat per tick
		#Range: > 0
		speedboat_energy_cost = 16

	[vehicle.Wheelchair]
		#The jump energy cost of the wheelchair
		#Range: > 0
		wheelchair_jump_energy_cost = 400
		#The move energy cost of the wheelchair
		#Range: > 0
		wheelchair_move_energy_cost = 1

	[vehicle.AH_6]
		#The min energy cost of AH-6 per tick
		#Range: > 0
		ah_6_min_energy_cost = 64
		#The max energy cost of AH-6 per tick
		#Range: > 0
		ah_6_max_energy_cost = 128
		#The cannon damage of AH-6
		#Range: 1.0 ~ 1.0E7
		ah_6_cannon_damage = 25.0
		#The cannon explosion damage of AH-6
		#Range: 1.0 ~ 1.0E7
		ah_6_cannon_explosion_damage = 12.0
		#The cannon explosion radius of AH-6
		#Range: 1.0 ~ 1.0E7
		ah_6_cannon_explosion_radius = 3.5
		#The rocket damage of AH-6
		#Range: 1.0 ~ 1.0E7
		ah_6_rocket_damage = 80.0
		#The rocket explosion damage of AH-6
		#Range: 1.0 ~ 1.0E7
		ah_6_rocket_explosion_damage = 40.0
		#The rocket explosion radius of AH-6
		#Range: 1.0 ~ 1.0E7
		ah_6_rocket_explosion_radius = 5.0
		#Whether to destroy the block when cannon of AH-6 hits a block
		ah_6_cannon_destroy = true

	[vehicle.LAV-150]
		#The energy cost of LAV-150 per tick
		#Range: > 0
		lav_150_energy_cost = 64
		#The cannon damage of LAV-150
		#Range: 1 ~ 10000000
		lav_150_cannon_damage = 45
		#The cannon explosion damage of LAV-150
		#Range: 1 ~ 10000000
		lav_150_cannon_explosion_damage = 12
		#The cannon explosion radius of LAV-150
		#Range: 1.0 ~ 1.0E7
		lav_150_cannon_explosion_radius = 4.0
		#The machine gun damage of LAV-150
		#Range: 1.0 ~ 1.0E7
		lav_150_machine_gun_damage = 9.5

	[vehicle.Tom-6]
		#The energy cost of Tom-6 per tick
		#Range: > 0
		tom_6_energy_cost = 16
		#The Melon Bomb explosion damage of Tom-6
		#Range: 1 ~ 10000000
		tom_6_bomb_explosion_damage = 500
		#The Melon Bomb explosion radius of Tom-6
		#Range: 1.0 ~ 1.0E7
		tom_6_bomb_explosion_radius = 10.0

	[vehicle.BMP-2]
		#The energy cost of BMP-2 per tick
		#Range: > 0
		bmp_2_energy_cost = 64
		#The cannon damage of BMP-2
		#Range: 1 ~ 10000000
		bmp_2_cannon_damage = 55
		#The cannon explosion damage of BMP-2
		#Range: 1 ~ 10000000
		bmp_2_cannon_explosion_damage = 15
		#The cannon explosion radius of BMP-2
		#Range: 1.0 ~ 1.0E7
		bmp_2_cannon_explosion_radius = 4.0

	[vehicle.YX-100]
		#The energy cost of YX-100 per tick
		#Range: > 0
		yx_100_energy_cost = 128
		#The energy cost of YX-100 per shoot
		#Range: > 0
		yx_100_shoot_cost = 24000
		#The cannon damage of YX-100
		#Range: 1 ~ 10000000
		yx_100_ap_cannon_damage = 500
		#The cannon explosion damage of YX-100
		#Range: 1 ~ 10000000
		yx_100_ap_cannon_explosion_damage = 100
		#The cannon explosion radius of YX-100
		#Range: 1.0 ~ 1.0E7
		yx_100_ap_cannon_explosion_radius = 4.0
		#The cannon damage of YX-100
		#Range: 1 ~ 10000000
		yx_100_he_cannon_damage = 150
		#The cannon explosion damage of YX-100
		#Range: 1 ~ 10000000
		yx_100_he_cannon_explosion_damage = 150
		#The cannon explosion radius of YX-100
		#Range: 1.0 ~ 1.0E7
		yx_100_he_cannon_explosion_radius = 10.0
		#The swarm drone explosion damage of YX-100
		#Range: 1 ~ 10000000
		yx_100_swarm_drone_explosion_damage = 80
		#The swarm drone explosion radius of YX-100
		#Range: 1.0 ~ 1.0E7
		yx_100_swarm_drone_explosion_radius = 5.0

	[vehicle."Prism Tank"]
		#The energy cost of Prism Tank per tick
		#Range: > 0
		prism_tank_energy_cost = 96
		#The Laser Damage of Prism Tank Mode 1
		#Range: > 0
		prism_tank_damage_mode_1 = 350
		#The energy cost of Prism Tank Mode 1
		#Range: 1 ~ 10000000
		prism_tank_shoot_cost_mode_1 = 100000
		#The laser AOE damage of Prism Tank
		#Range: 1 ~ 10000000
		prism_tank_aoe_damage = 72
		#The laser AOE radius of Prism Tank
		#Range: 1 ~ 10000000
		prism_tank_aoe_radius = 12
		#The Laser Damage of Prism Tank Mode 2 per tick
		#Range: 1 ~ 10000000
		prism_tank_damage_mode_2 = 15
		#The energy cost of Prism Tank Mode 2 per tick
		#Range: 1 ~ 10000000
		prism_tank_shoot_cost_mode_2 = 5000

	[vehicle.HPJ-11]
		#The damage of HPJ-11
		#Range: 1.0 ~ 1.0E7
		hpj_11_damage = 20.0
		#The explosion damage of HPJ-11
		#Range: 1.0 ~ 1.0E7
		hpj_11_explosion_damage = 7.0
		#The explosion radius of HPJ-11
		#Range: 1.0 ~ 50.0
		hpj_11_explosion_radius = 4.0
		#The energy cost of HPJ-11 per shoot
		#Range: > 0
		hpj_11_shoot_cost = 64
		#The energy cost of HPJ-11 find a new target
		#Range: > 0
		hpj_11_seek_cost = 1024

	[vehicle.A-10]
		#The max energy cost of A-10 per tick
		#Range: > 0
		A_10_max_energy_cost = 256
		#The cannon damage of A-10
		#Range: 1 ~ 10000000
		A_10_cannon_damage = 30
		#The cannon explosion damage of A-10
		#Range: 1 ~ 10000000
		A_10_cannon_explosion_damage = 10
		#The cannon explosion radius of A-10
		#Range: 1.0 ~ 1.0E7
		A_10_cannon_explosion_radius = 4.0
		#The rocket damage of A-10
		#Range: 1 ~ 10000000
		A_10_rocket_damage = 90
		#The rocket explosion damage of A-10
		#Range: 1 ~ 10000000
		A_10_rocket_explosion_damage = 50
		#The rocket explosion radius of A-10
		#Range: 1.0 ~ 1.0E7
		A_10_rocket_explosion_radius = 6.0

[misc]
	#Set true to enable tactical sprint
	allow_tactical_sprint = false
	#Set true to enable kill feedback sending
	send_kill_feedback = true
	#Set true to enable force damage
	allow_force_damage = false
	#The default maximum armor level for normal armors
	#Range: 0 ~ 10000000
	default_armor_level = 1
	#The maximum armor level for armors with superbwarfare:military_armor tag
	#Range: 0 ~ 10000000
	military_armor_level = 2
	#The maximum armor level for armors with superbwarfare:military_armor_heavy tag(will override superbwarfare:military_armor tag!)
	#Range: 0 ~ 10000000
	heavy_military_armor_level = 3
	#The points per level for armor plate
	#Range: 0 ~ 10000000
	armor_point_per_level = 15
	#Max energy storage of charging station
	#Range: > 1
	charging_station_max_energy = 4000000
	#How much FE energy can charging station generate per tick
	#Range: > 1
	charging_station_generate_speed = 128
	#How much FE energy can charging station transfer per tick
	#Range: > 1
	charging_station_transfer_speed = 100000
	#The charging radius of the charging station
	#Range: 0 ~ 128
	charging_station_charge_radius = 8
	#The default fuel time of the charging station
	#Range: > 1
	charging_station_default_fuel_time = 1600
	#The max size of artillery indicator binding list
	#Range: > 1
	artillery_indicator_list_size = 32

[seek]
	#List of entities that can NOT be sought
	seek_blacklist = ["minecraft:item", "minecraft:experience_orb", "minecraft:armor_stand", "minecraft:area_effect_cloud", "superbwarfare:claymore", "superbwarfare:c4", "touhou_little_maid:power_point", "evilcraft:vengeance_spirit", "mts:builder_rendering"]

